### PR TITLE
Flexstatistics

### PR DESCRIPTION
**Pull request by tomatell**
[Review on Reviewable](https://reviewable.io/reviews/membery/data-szh/43)

### CODE REVIEW

**Comment by sosik** [comment]
tom please review pull and include only reated stuff



---

Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[partials/x-main-menu.html, line 105 [r1]](https://reviewable.io:443/reviews/membery/data-szh/43#-K2lyrUoi_iiKc351x95)** ([raw file](https://github.com/membery/data-szh/blob/52a5d2fa9a1c4b56fd17d1145bb1b7a8d961a9bc/partials/x-main-menu.html#L105)):</sup>
This change depends on previous commit and it should not, please remove it form this pull



---

<sup>**[portal/templates/index.html, line 20 [r1]](https://reviewable.io:443/reviews/membery/data-szh/43#-K2lz92IKQuwAUd39kLa)** ([raw file](https://github.com/membery/data-szh/blob/52a5d2fa9a1c4b56fd17d1145bb1b7a8d961a9bc/portal/templates/index.html#L20)):</sup>
this belongs to different pull, please remove it



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/membery/data-szh/43)

**Comment by tomatell** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[partials/x-main-menu.html, line 105 [r1]](https://reviewable.io:443/reviews/membery/data-szh/43#-K2lyrUoi_iiKc351x95)** ([raw file](https://github.com/membery/data-szh/blob/52a5d2fa9a1c4b56fd17d1145bb1b7a8d961a9bc/partials/x-main-menu.html#L105)):</sup>
It has been removed.



---

<sup>**[portal/templates/index.html, line 20 [r1]](https://reviewable.io:443/reviews/membery/data-szh/43#-K2lz92IKQuwAUd39kLa)** ([raw file](https://github.com/membery/data-szh/blob/52a5d2fa9a1c4b56fd17d1145bb1b7a8d961a9bc/portal/templates/index.html#L20)):</sup>
It has been removed.



---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/membery/data-szh/43)

**Comment by tomatell** [comment]
It has been rebased and unnecessary commits were removed.



---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/membery/data-szh/43)

**Comment by sosik** [comment]
Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/membery/data-szh/43)

**Comment by sosik** [comment]
merged

**Pull request closed without merging**
